require:
  - rubocop-rspec

inherit_gem:
  rspec-sleeping_king_studios: config/rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

RSpec:
  Include:
    - '**/*_examples.rb'
    - '**/*_contract.rb'
    - '**/*_spec.rb'
    - '**/*_spec.fixture.rb'
    - '**/*_spec.fixtures.rb'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineContinuationLeadingSpace:
  Enabled: false

Layout/LineLength:
  AllowedPatterns:
    - '\A\s*#'
  Max: 80

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - Gemfile

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/BeNil:
  Enabled: false

RSpec/Eq:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/ExampleWording:
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: example

RSpec/LeadingSubject:
  Enabled: false # Expects subject to precede shared examples.

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/RepeatedDescription:
  # Does not recognize :wrap_context nodes.
  Enabled: false

RSpec/RepeatedExample:
  # Does not recognize :wrap_context nodes.
  Enabled: false

RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/integration/**/*.rb'

RSpec/SpecFilePathSuffix:
  Exclude:
    - '**/*spec.fixture.rb'
    - '**/*spec.fixtures.rb'

Style/AccessorGrouping:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ClassAndModuleChildren:
  # Checks the style of children definitions at classes and modules.
  #
  # Our preferred style is compact-plus-one, which does not match any of the
  # existing styles, so we disable this cop.
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MultilineBlockChain:
  # Incompatible with operation then/else syntax.
  Enabled: false

Style/NestedParenthesizedCalls:
  # This cop is excessively strict, especially in cases where the nested method
  # call has only one argument, e.g. outer_method(inner_method arg). Adding the
  # inner parentheses reduces readability.
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'spec/**/*.rb'

Style/SingleLineBlockParams:
  # Prefer descriptive block param names.
  Enabled: false

Style/TrailingUnderscoreVariable:
  # Prefer more explicit syntax when ignoring destructured results.
  Enabled: false
