# Build Options
language: ruby
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
before_script:
  - cp .rspec.example .rspec
script:
  - bundle exec thor ci:steps

# Travis-CI Configuration
cache: bundler
sudo:  false # Enable containerized builds.
