# Build Options
language: ruby
rvm:
  - 2.6.8
  - 2.7.4
  - 3.0.2
before_install:
  - sudo apt-get update && sudo apt-get install apt-transport-https ca-certificates -y && sudo update-ca-certificates
before_script:
  - cp .rspec.example .rspec
script:
  - bundle exec thor ci:steps

# Travis-CI Configuration
cache: bundler
dist: focal
