# frozen_string_literal: true

source 'https://rubygems.org'

gem 'byebug'
gem 'github-pages', group: :jekyll_plugins
gem 'jekyll-docs'
gem 'rake'
gem 'sleeping_king_studios-yard',
  path: '../../sleeping_king_studios-yard'
  # branch:  'main',
  # git:     'https://github.com/sleepingkingstudios/sleeping_king_studios-yard',
  # require: false
gem 'webrick'

ruby '3.1.3'
